
version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.READER_TOKEN }}
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    registries: '*'
    ignore:
      - dependency-name: 'eslint'
        versions: [ '9.x' ]
    groups:
      aksel-dependencies:
        patterns:
          - '@navikt/aksel*'
          - '@navikt/ds*'
      react-dependencies:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      team-deps:
        patterns:
          - '@navikt/aap-felles*'
      testing:
        patterns:
          - 'vitest'
          - 'vitest-fetch-mock'
          - '@vitest/coverage-v8'
          - '@vitejs/plugin-react'
          - '@testing-library/react'
          - '@testing-library/user-event'
          - '@testing-library/dom'
          - '@testing-library/jest-dom'
          - 'jsdom'
