apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "produksjonsstyring"
  namespace: "aap"
  labels:
    "team": "aap"
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: "/api/internal/isAlive"
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/api/internal/isReady"
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 4
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 512Mi
  observability:
    tracing:
      enabled: true
    logging:
      destinations:
        - id: elastic
        - id: loki
  azure:
    application:
      enabled: true
      allowAllUsers: true
    sidecar:
      enabled: true
      autoLogin: true
  accessPolicy:
    outbound:
      rules:
        - application: statistikk
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  env:
  {{#each env}}
     - name: {{this.name }}
  value: {{this.value}}
  {{/each}}
