apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "produksjonsstyring"
  namespace: "aap"
  labels:
    "team": "aap"
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: "/oppgave/api/internal/isAlive"
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/oppgave/api/internal/isReady"
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 4
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 512Mi
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: elastic
        - id: loki
  azure:
    application:
      enabled: true
      allowAllUsers: true
  accessPolicy:
    inbound:
      rules:
        - application: "kelvin-reverse-proxy"
    outbound:
      rules:
        - application: oppgave
        - application: behandlingsflyt
        - application: statistikk
      external:
        - host: "cdn.nav.no"
  env:
  {{#each env}}
     - name: {{this.name }}
  value: {{this.value}}
  {{/each}}
