import { AvklaringsbehovKode } from 'lib/types/types';

export const avklaringsbehovOptions = [
  'Avklar student (§ 11-14)',
  'Avklar sykdom (§ 11-5)',
  'Vurdering av etablert og uutnyttet arbeidsevne (§ 11-23)',
  'Fritak meldeplikt (§ 11-10)',
  'Avklar bistandsbehov (§ 11-6)',
  'Vurder sykepengeerstatning (§ 11 -13)',
  'Fastsett beregningstidspunkt',
  'Avklar barnetillegg',
  'Foreslå vedtak',
  'Fatte vedtak',
  'Kvalitetssikring',
  'Manuelt satt på vent',
  'Bestill brev',
  'Bestill legeerklæring',
  'Avklar soningsvurdering',
  'Avklar helseinstitusjon',
  'Avklar samordning gradering',
  'Avklar yrkesskade',
  'Fastsett yrkesskadebeløp',
  'Skriv brev',
  'Kategoriser dokument',
  'Digitaliser dokument',
  'Avklar tema',
  'Avklar saksnummer',
  'Endre tema',
];
export const avklaringsbehovKoder: AvklaringsbehovKode[] = [
  '5001',
  '5003',
  '5004',
  '5005',
  '5006',
  '5007',
  '5008',
  '5009',
  '5098',
  '5099',
  '5097',
  '9001',
  '9002',
  '9003',
  '5010',
  '5011',
  '5012',
  '5013',
  '5014',
  '5050',
  '1337',
  '1338',
  '1339',
  '1340',
  '1341',
];
export const avklaringsbehovKodeOgLabel = [
  { value: '5001', label: 'Avklar student (§ 11-14)' },
  { value: '5003', label: 'Avklar sykdom (§ 11-5)' },
  { value: '5004', label: 'Vurdering av etablert og uutnyttet arbeidsevne (§ 11-23)' },
  { value: '5005', label: 'Fritak meldeplikt (§ 11-10)' },
  { value: '5006', label: 'Avklar bistandsbehov (§ 11-6)' },
  { value: '5007', label: 'Vurder sykepengeerstatning (§ 11 -13)' },
  { value: '5008', label: 'Fastsett beregningstidspunkt' },
  { value: '5009', label: 'Avklar barnetillegg' },
  { value: '5098', label: 'Foreslå vedtak' },
  { value: '5099', label: 'Fatte vedtak' },
  { value: '5097', label: 'Kvalitetssikring' },
  { value: '9001', label: 'Manuelt satt på vent' },
  { value: '9002', label: 'Bestill brev' },
  { value: '9003', label: 'Bestill legeerklæring' },
  { value: '5010', label: 'Avklar soningsvurdering' },
  { value: '5011', label: 'Avklar helseinstitusjon' },
  { value: '5012', label: 'Avklar samordning gradering' },
  { value: '5013', label: 'Avklar yrkesskade' },
  { value: '5014', label: 'Fastsett yrkesskadebeløp' },
  { value: '5050', label: 'Skriv brev' },
  { value: '1337', label: 'Kategoriser dokument' },
  { value: '1338', label: 'Digitaliser dokument' },
  { value: '1339', label: 'Avklar tema' },
  { value: '1340', label: 'Avklar saksnummer' },
  { value: '1341', label: 'Endre tema' },
];
export type AvklaringsbehovLabel = (typeof avklaringsbehovOptions)[number];
