name: Update dependabot config

on:
  workflow_dispatch:

jobs:
  checkForConfigUpdate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: ./my-repo
      - uses: actions/checkout@v4
        with:
          repository: navikt/aap-workflows
          path: ./aap-workflows
          token: ${{ secrets.github_token }}
      - name: check diff
        id: check-diff
        run: |
          DIFF_STATUS="$(cmp --silent $./my-repo/.github/dependabot.yml $./aap-workflows/.github/workflows/dependabot-frontend-next.yml; echo $?)"
          echo "Files differ: $DIFF_STATUS"
          echo "DIFF_STATUS=$DIFF_STATUS" >> $GITHUB_ENV
      - if: env.DIFF_STATUS != 0
        run: |
          cd my-repo
          git config --global user.email "aap-dependabot-updater@nav.no"
          git config --global user.name "AAP felles dependabot config sync"
          git checkout -b dependabot-config-update
          cp -f ../aap-workflows/.github/workflows/dependabot-frontend-next.yml ./.github/dependabot.yml 
          git add .
          git commit -m "oppdatert dependabot config"
          gh pr create --head --title "Dependabot config" --body ":construction_worker: Ny config hentet fra navikt/aap-workflows dependabot-frontend-next.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
